### ISSUE TITLE
[Rails 5] Deprecation warnings

### ISSUE THREAD

**Issue by anthony-robin** [weppos/actionmailer_with_request#12]
Using this gem with Rails 5 throw a deprecation warnings:

```bash
# before_filter => before_action
DEPRECATION WARNING: before_filter is deprecated and will be removed in Rails 5.1. 
Use before_action instead.

# alias_method_chain => Module#prepend
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead.
From module, you can access the original method using super.
```

**Comment by eric1234** [comment]
This is actually fixed in PR #11 ....

**Comment by anthony-robin** [comment]
When does your PR will be merged ?

**Comment by weppos** [comment]
Merged.

**Comment by anthony-robin** [comment]
Thanks ! 
And about the gem any new release will be published to rubygems ?

**Comment by weppos** [comment]
Try to use master and let me know if it works.

**Comment by anthony-robin** [comment]
Actually, using master branch give me this error when running my tests:

```bash
# Extract of error
.rvm/gems/ruby-2.3.0/bundler/gems/actionmailer_with_request-3cf48f13aad8/lib/actionmailer_with_request.rb:1:in `require_relative': 
cannot load such file -- /.rvm/gems/ruby-2.3.0/bundler/gems/actionmailer_with_request-3cf48f13aad8/lib/version (LoadError)
from /.rvm/gems/ruby-2.3.0/bundler/gems/actionmailer_with_request-3cf48f13aad8/lib/actionmailer_with_request.rb:1:in `<top (required)>'
```

**Comment by weppos** [comment]
Thanks, it should be fixed now.

**Comment by anthony-robin** [comment]
still broken:
```bash
There was an error while trying to load the gem 'actionmailer-with-request'. (Bundler::GemRequireError)
Gem Load Error is: wrong number of arguments (given 0, expected 1)
Backtrace for gem load error is:
.rvm/gems/ruby-2.3.0/bundler/gems/actionmailer_with_request-10c0e2e15ba3/lib/actionmailer_with_request.rb:6:in `included'
...
```
